 CREATE TABLE Log(
   id int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   program_id int NOT NULL,
   start_date DATE NOT NULL,
   end_date DATE
 );
--
 CREATE TABLE LOG_CLASS
 (
   id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
   log_id INT NOT NULL,
   class_id INT NOT NULL
 );
--
CREATE TABLE YOGA_CLASS
(
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  date DATE NOT NULL,
  class_name VARCHAR(50) NOT NULL,
  teacher_name VARCHAR(50) NOT NULL,
  studio_name VARCHAR(50) NOT NULL,
  hours DOUBLE NOT NULL
);
--
 ALTER TABLE LOG_CLASS
   ADD CONSTRAINT LOG_CLASS_LOG__fk
 FOREIGN KEY (LOG_ID) REFERENCES LOG (ID);
-- --
 ALTER TABLE LOG_CLASS
   ADD CONSTRAINT LOG_CLASS_YOGA_CLASS__fk
 FOREIGN KEY (CLASS_ID) REFERENCES YOGA_CLASS (ID);

INSERT INTO YOGA_CLASS (date, class_name, teacher_name, studio_name, hours)
    VALUES ('2018-06-09', 'Yoga I', 'Janis Sheldon', 'YogaLife', 1.5 ),
          ('2018-06-05', 'Yoga II', 'Marissa McAleer', 'YogaLife', 1.5);

